name: hamanieh_flash
description: "Hamanieh Flash.net - Votre radio + Vos actualités + Vos vidéos"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Réseau / API vers votre backend existant
  http: ^1.2.0
  dio: ^5.4.0

  # Lecture audio (radio en direct)
  just_audio: ^0.9.36

  # Gestion d'état simple
  provider: ^6.1.1

  # Utilitaires
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  url_launcher: ^6.2.4
  share_plus: ^10.1.4
  timeago: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
