name: Build APK Android

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter create --platforms=android --org net.hamaniehflash .

      - name: Forcer Android SDK 36
        run: |
          for f in android/app/build.gradle.kts android/app/build.gradle; do
            if [ -f "$f" ]; then
              sed -i -E 's/compileSdk[[:space:]]*=[[:space:]]*flutter\.compileSdkVersion/compileSdk = 36/' "$f"
              sed -i -E 's/compileSdkVersion[[:space:]]+flutter\.compileSdkVersion/compileSdkVersion 36/' "$f"
              sed -i -E 's/targetSdk[[:space:]]*=[[:space:]]*flutter\.targetSdkVersion/targetSdk = 36/' "$f"
              sed -i -E 's/targetSdkVersion[[:space:]]+flutter\.targetSdkVersion/targetSdkVersion 36/' "$f"
              echo "----- Contenu de $f après modification -----"
              cat "$f"
            fi
          done

      - run: flutter pub get
      - run: flutter build apk --release

      - uses: actions/upload-artifact@v4
        with:
          name: hamanieh-flash-test-apk
          path: build/app/outputs/apk/release/app-release.apk
